name: Feature five workflow

on:
  workflow_dispatch:
  workflow_call:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
      
jobs:
  feature-five-run:
    name: Feature Five
    runs-on: ubuntu-20.04
    steps:
      - run: |
          echo "feature five"
