name: Test run jobs when merged

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
      
jobs:
  normal-run:
    name: Job that normal run
    runs-on: ubuntu-20.04
    steps:
      - run: |
          echo "normal run"
          echo "github.event_name ${{ github.event_name }}"
          echo "github.event.action ${{ github.event.action }}"
          echo "github.ref_name ${{ github.ref_name }}"
          echo "github.ref ${{ github.ref }}"

  merge-run:
    name: Job that after merge
    if: ${{ (github.ref_name == 'main') && github.event_name == 'push' }} 
    runs-on: ubuntu-20.04
    steps:
        - run: |
            echo "run after merge"

  trigger-feature-five:
    uses: ./.github/workflows/feature-five-workflow.yml
