name: Test run jobs when merged

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
      
jobs:
  normal-run:
    name: Job that normal run
    runs-on: ubuntu-20.04
    steps:
      - run: |
          echo "normal run"
          echo "event ${{ github.event_name }}"
          echo "event ${{ github.ref_name }}"
          echo "event ${{ github.ref }}"

  merge-run:
    name: Job that after merge
    runs-on: ubuntu-20.04
    steps:
      - if: ${{ github.event_name }} == 'push' && ${{ github.ref_name }} == 'main'
        run: |
          echo "run after merge"
