name: Test run jobs when merged

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
      
jobs:
  normal-run:
    name: Job that normal run
    runs-on: ubuntu-20.04
    steps:
      - run: |
          echo "normal run"

  merge-run:
    name: Job that normal run
    runs-on: ubuntu-20.04
    steps:
      - if: ${{ github.event_name }} == 'push' && ${{ github.ref_name }} == 'main'
        run: |
          echo "run after merge"
